Mona/config/routes.rb
Rails.application.routes.draw do
  resources :mensajes
  resources :rols
  resources :usuarios
  resources :tweets
  resources :twets
  resources :articulos
  resources :clientes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

Mona/app/controllers/twets_controller.rb
class TwetsController < ApplicationController
  before_action :set_twet, only: %i[ show edit update destroy ]

  # GET /twets or /twets.json
  def index
    @twets = Twet.all
  end

  # GET /twets/1 or /twets/1.json
  def show
  end

  # GET /twets/new
  def new
    @twet = Twet.new
  end

  # GET /twets/1/edit
  def edit
  end

  # POST /twets or /twets.json
  def create
    @twet = Twet.new(twet_params)

    respond_to do |format|
      if @twet.save
        format.html { redirect_to @twet, notice: "Twet was successfully created." }
        format.json { render :show, status: :created, location: @twet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @twet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /twets/1 or /twets/1.json
  def update
    respond_to do |format|
      if @twet.update(twet_params)
        format.html { redirect_to @twet, notice: "Twet was successfully updated." }
        format.json { render :show, status: :ok, location: @twet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @twet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /twets/1 or /twets/1.json
  def destroy
    @twet.destroy
    respond_to do |format|
      format.html { redirect_to twets_url, notice: "Twet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_twet
      @twet = Twet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def twet_params
      params.require(:twet).permit(:content)
    end
end

Mona/app/helpers/twets_helper.rb
module TwetsHelper
end

Mona/app/views/twets/_form.html.erb
<%= form_with(model: twet) do |form| %>
  <% if twet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(twet.errors.count, "error") %> prohibited this twet from being saved:</h2>

      <ul>
        <% twet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Mona/app/views/twets/edit.html.erb
<h1>Editing Twet</h1>

<%= render 'form', twet: @twet %>

<%= link_to 'Show', @twet %> |
<%= link_to 'Back', twets_path %>

Mona/app/views/twets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Twets</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @twets.each do |twet| %>
      <tr>
        <td><%= twet.content %></td>
        <td><%= link_to 'Show', twet %></td>
        <td><%= link_to 'Edit', edit_twet_path(twet) %></td>
        <td><%= link_to 'Destroy', twet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Twet', new_twet_path %>

Mona/app/views/twets/new.html.erb
<h1>New Twet</h1>

<%= render 'form', twet: @twet %>

<%= link_to 'Back', twets_path %>

Mona/app/views/twets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @twet.content %>
</p>

<%= link_to 'Edit', edit_twet_path(@twet) %> |
<%= link_to 'Back', twets_path %>